const data = {
    total_province: 34,
    provinces: [
      {
        name: "Jakarta",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Jawa Barat",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Jawa Tengah",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Jawa Timur",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Banten",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Yogyakarta",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Kalimantan Timur",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Bali",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sumatera Utara",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Riau",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sulawesi Selatan",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sumatera Barat",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Nusa Tenggara Timur",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Kalimantan Selatan",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sumatera Selatan",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Lampung",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Kepulauan Riau",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Bangka Belitung",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Kalimantan Barat",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sulawesi Tengah",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Kalimantan Tengah",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sulawesi Utara",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Papua",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Kalimantan Utara",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Aceh",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Jambi",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Nusa Tenggara Barat",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Papua Barat",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Bengkulu",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sulawesi Tenggara",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Maluku",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Sulawesi Barat",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Maluku Utara",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
      {
        name: "Gorontalo",
        positive: 0,
        recovered: 0,
        death: 0,
        hospitalized: 0,
      },
    ],
};
  
export default data;
  